window.CO_DATA = {
  deptos: [
    { code: 5, name: 'Antioquia', capital: 'Medellin', municipios: [{ code: 5001, name: 'Medellin' }, { code: 5002, name: 'Abejorral' }, { code: 5031, name: 'Amalfi' }] },
    { code: 8, name: 'Atlantico', capital: 'Barranquilla', municipios: [{ code: 8001, name: 'Barranquilla' }, { code: 8078, name: 'Baranoa' }, { code: 8758, name: 'Soledad' }] },
    { code: 11, name: 'Bogota, D.C.', capital: 'Bogota, D.C.', municipios: [{ code: 11001, name: 'Bogota, D.C.' }] },
    { code: 13, name: 'Bolivar', capital: 'Cartagena de Indias', municipios: [{ code: 13001, name: 'Cartagena de Indias' }, { code: 13052, name: 'Arjona' }, { code: 13836, name: 'Turbaco' }] },
    { code: 15, name: 'Boyaca', capital: 'Tunja', municipios: [{ code: 15001, name: 'Tunja' }, { code: 15087, name: 'Belen' }, { code: 15407, name: 'Villa de Leyva' }] },
    { code: 17, name: 'Caldas', capital: 'Manizales', municipios: [{ code: 17001, name: 'Manizales' }, { code: 17013, name: 'Aguadas' }, { code: 17433, name: 'La Dorada' }] },
    { code: 18, name: 'Caqueta', capital: 'Florencia', municipios: [{ code: 18001, name: 'Florencia' }, { code: 18029, name: 'Albania' }, { code: 18410, name: 'La Montanita' }] },
    { code: 19, name: 'Cauca', capital: 'Popayan', municipios: [{ code: 19001, name: 'Popayan' }, { code: 19022, name: 'Almaguer' }, { code: 19807, name: 'Timbio' }] },
    { code: 20, name: 'Cesar', capital: 'Valledupar', municipios: [{ code: 20001, name: 'Valledupar' }, { code: 20011, name: 'Aguachica' }, { code: 20570, name: 'Pueblo Bello' }] },
    { code: 23, name: 'Cordoba', capital: 'Monteria', municipios: [{ code: 23001, name: 'Monteria' }, { code: 23068, name: 'Ayapel' }, { code: 23660, name: 'Sahagun' }] },
    { code: 25, name: 'Cundinamarca', capital: 'Bogota, D.C.', municipios: [{ code: 25001, name: 'Agua de Dios' }, { code: 25175, name: 'Chia' }, { code: 25754, name: 'Soacha' }] },
    { code: 27, name: 'Choco', capital: 'Quibdo', municipios: [{ code: 27001, name: 'Quibdo' }, { code: 27006, name: 'Acandi' }, { code: 27495, name: 'Nuqui' }] },
    { code: 41, name: 'Huila', capital: 'Neiva', municipios: [{ code: 41001, name: 'Neiva' }, { code: 41006, name: 'Acevedo' }, { code: 41551, name: 'Pitalito' }] },
    { code: 44, name: 'La Guajira', capital: 'Riohacha', municipios: [{ code: 44001, name: 'Riohacha' }, { code: 44035, name: 'Albania' }, { code: 44874, name: 'Uribia' }] },
    { code: 47, name: 'Magdalena', capital: 'Santa Marta', municipios: [{ code: 47001, name: 'Santa Marta' }, { code: 47030, name: 'Algarrobo' }, { code: 47288, name: 'Fundacion' }] },
    { code: 50, name: 'Meta', capital: 'Villavicencio', municipios: [{ code: 50001, name: 'Villavicencio' }, { code: 50006, name: 'Acacias' }, { code: 50680, name: 'San Martin' }] },
    { code: 52, name: 'Narino', capital: 'Pasto', municipios: [{ code: 52001, name: 'Pasto' }, { code: 52022, name: 'Aldana' }, { code: 52835, name: 'Tumaco' }] },
    { code: 54, name: 'Norte de Santander', capital: 'Cucuta', municipios: [{ code: 54001, name: 'Cucuta' }, { code: 54003, name: 'Abrego' }, { code: 54874, name: 'Villa del Rosario' }] },
    { code: 63, name: 'Quindio', capital: 'Armenia', municipios: [{ code: 63001, name: 'Armenia' }, { code: 63111, name: 'Buenavista' }, { code: 63548, name: 'Montenegro' }] },
    { code: 66, name: 'Risaralda', capital: 'Pereira', municipios: [{ code: 66001, name: 'Pereira' }, { code: 66045, name: 'Apia' }, { code: 66400, name: 'La Virginia' }] },
    { code: 68, name: 'Santander', capital: 'Bucaramanga', municipios: [{ code: 68001, name: 'Bucaramanga' }, { code: 68013, name: 'Aguada' }, { code: 68679, name: 'San Gil' }] },
    { code: 70, name: 'Sucre', capital: 'Sincelejo', municipios: [{ code: 70001, name: 'Sincelejo' }, { code: 70011, name: 'Buenavista' }, { code: 70820, name: 'Santiago de Tolu' }] },
    { code: 73, name: 'Tolima', capital: 'Ibague', municipios: [{ code: 73001, name: 'Ibague' }, { code: 73024, name: 'Alpujarra' }, { code: 73449, name: 'Melgar' }] },
    { code: 76, name: 'Valle del Cauca', capital: 'Cali', municipios: [{ code: 76001, name: 'Cali' }, { code: 76109, name: 'Buenaventura' }, { code: 76834, name: 'Tulua' }] },
    { code: 81, name: 'Arauca', capital: 'Arauca', municipios: [{ code: 81001, name: 'Arauca' }, { code: 81065, name: 'Arauquita' }, { code: 81736, name: 'Saravena' }] },
    { code: 85, name: 'Casanare', capital: 'Yopal', municipios: [{ code: 85001, name: 'Yopal' }, { code: 85010, name: 'Aguazul' }, { code: 85440, name: 'Mani' }] },
    { code: 86, name: 'Putumayo', capital: 'Mocoa', municipios: [{ code: 86001, name: 'Mocoa' }, { code: 86219, name: 'Colon' }, { code: 86757, name: 'San Miguel' }] },
    { code: 88, name: 'Archipielago de San Andres, Providencia y Santa Catalina', capital: 'San Andres', municipios: [{ code: 88001, name: 'San Andres' }, { code: 88564, name: 'Providencia' }] },
    { code: 91, name: 'Amazonas', capital: 'Leticia', municipios: [{ code: 91001, name: 'Leticia' }, { code: 91263, name: 'El Encanto' }, { code: 91460, name: 'Miriti - Parana' }] },
    { code: 94, name: 'Guainia', capital: 'Inirida', municipios: [{ code: 94001, name: 'Inirida' }, { code: 94343, name: 'Barrancominas' }] },
    { code: 95, name: 'Guaviare', capital: 'San Jose del Guaviare', municipios: [{ code: 95001, name: 'San Jose del Guaviare' }, { code: 95015, name: 'Calamar' }, { code: 95200, name: 'Miraflores' }] },
    { code: 97, name: 'Vaupes', capital: 'Mitu', municipios: [{ code: 97001, name: 'Mitu' }, { code: 97161, name: 'Caruru' }, { code: 97777, name: 'Papunahua' }] },
    { code: 99, name: 'Vichada', capital: 'Puerto Carreno', municipios: [{ code: 99001, name: 'Puerto Carreno' }, { code: 99524, name: 'La Primavera' }, { code: 99773, name: 'Cumaribo' }] }
  ]
};
